"""Añadir columna image_file a la tabla product

Revision ID: 3fb59995c7e6
Revises: 20a7338b1c4e
Create Date: 2025-11-19 21:13:53.814959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb59995c7e6'
down_revision = '20a7338b1c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
